### ISSUE TITLE
[tasks] periodo de codificación 2

### ISSUE THREAD

**Issue by vchrombie** [vchrombie/gsoc#12]
- [x] Implement pipermailqm enricher
  - [x] discuss what metrics can be extracted from git #11 
  - [x] implement the enrichers which can extract the metrics #6 
  - [x] show results https://github.com/vchrombie/gsoc/issues/12#issuecomment-666701453

- [x] Implement meetupqm enricher
  - [x] discuss what metrics can be extracted from git #14 
  - [x] implement the enrichers which can extract the metrics #6 
  - [x] show results https://github.com/vchrombie/gsoc/issues/12#issuecomment-666701453

- [x] perform an assessment https://github.com/vchrombie/gsoc/issues/5#issuecomment-650801828
  - [x] plot heat maps and bar charts with prosoul assessment results https://github.com/vchrombie/gsoc/issues/12#issuecomment-654420431

- [x] case study with different organizations #13 
  - [x] amfoss - gitlabqm, gitqm https://github.com/vchrombie/gsoc/issues/13#issuecomment-656187839
~~- [ ] gitlab.org - gitlabqm, gitqm, meetupqm~~ (moved to coding period 3)

~~- [ ] Implements tests for the existing enrichers #15~~ (moved to coding period 3)

**Comment by vchrombie** [comment]
![Screenshot_20200704_040854](https://user-images.githubusercontent.com/25265451/86500576-c7f6fb00-bdaf-11ea-8bf7-c24cdaed2641.png)
![Screenshot_20200704_040906](https://user-images.githubusercontent.com/25265451/86500579-c9c0be80-bdaf-11ea-99ee-fffa35bb07cc.png)
![Screenshot_20200704_040917](https://user-images.githubusercontent.com/25265451/86500581-caf1eb80-bdaf-11ea-97ff-cd6335c06864.png)
![Screenshot_20200704_040927](https://user-images.githubusercontent.com/25265451/86500584-cb8a8200-bdaf-11ea-9ae6-d469c1a8cdba.png)
![Screenshot_20200704_040941](https://user-images.githubusercontent.com/25265451/86500586-ccbbaf00-bdaf-11ea-8ee0-47d71013d1d0.png)

**Comment by vchrombie** [comment]
Updated the dashboards

![Screenshot_20200706_143005](https://user-images.githubusercontent.com/25265451/86631665-0842bd00-bfec-11ea-940c-1c814befc2f0.png)
![Screenshot_20200706_143022](https://user-images.githubusercontent.com/25265451/86631674-0aa51700-bfec-11ea-9167-6a5488a315f0.png)
![Screenshot_20200706_143044](https://user-images.githubusercontent.com/25265451/86631677-0b3dad80-bfec-11ea-8b82-d3e1d73cc677.png)
![Screenshot_20200706_143055](https://user-images.githubusercontent.com/25265451/86631681-0c6eda80-bfec-11ea-9d06-9eabc1a54075.png)

**Comment by vchrombie** [comment]
pipermailqm results

![Screenshot_20200731_010908](https://user-images.githubusercontent.com/25265451/88974773-c77e5100-d2d6-11ea-8c9c-df3898899b8b.png)
![Screenshot_20200731_010939](https://user-images.githubusercontent.com/25265451/88974785-cbaa6e80-d2d6-11ea-8cf7-436f1486ee41.png)

meetupqm results

![Screenshot_20200731_015122](https://user-images.githubusercontent.com/25265451/88974799-cfd68c00-d2d6-11ea-8d85-c342a4ae820a.png)
![Screenshot_20200731_015110](https://user-images.githubusercontent.com/25265451/88974793-ce0cc880-d2d6-11ea-97d5-1c6a964ff8d3.png)

**Comment by vchrombie** [comment]
completed the planned tasks, so closing this issue
