### ISSUE TITLE
[assessments] perform assessments on various projects of different organizations

### ISSUE THREAD

**Issue by vchrombie** [vchrombie/gsoc#13]
opening this, in reference to the task planned in the last meeting, to discuss performing of assessments on a various set of projects

- [x] pilot study 1: amFOSS (gitlab, git) https://github.com/vchrombie/gsoc/issues/13#issuecomment-656187839
- [x] pilot study 2: GitLab.org (gitlab, meetup) https://github.com/vchrombie/gsoc/issues/13#issuecomment-669236168
- [x] pilot study 3: CHAOSS Community (git, github) https://github.com/vchrombie/gsoc/issues/13#issuecomment-674578813

**Comment by vchrombie** [comment]
pilot study :small_airplane: on [amFOSS](https://amfoss.in/) projects
data sources: gitlab, git
quality model: Developer QM

![amfoss-dashboard-1](https://user-images.githubusercontent.com/25265451/87469797-76fdc700-c639-11ea-9539-f4331f93ea99.png)
![amfoss-dashboard-2](https://user-images.githubusercontent.com/25265451/87469801-79602100-c639-11ea-9f9e-30a7cdf1ed75.png)
![amfoss-dashboard-3](https://user-images.githubusercontent.com/25265451/87469805-79f8b780-c639-11ea-8636-cc3457fd7153.png)
![amfoss-dashboard-4](https://user-images.githubusercontent.com/25265451/87469809-7bc27b00-c639-11ea-92a4-f7e835c3a9e2.png)

**Comment by vchrombie** [comment]
I'm performing a pilot study on the GitLab.org projects. The involved data sources are gitlab and meetup. I was facing a few errors during the enrichment, most of them were flaws in the implementation. I have been fixing them. But, I couldn't fix one error.

```
  2020-08-04 20:25:59,206 160 items inserted for GitLab QM
  2020-08-04 20:25:59,207 [gitlabqm] Done enrichment for https://gitlab.com/gitlab-org/gitlab-omnibus-builder
  2020-08-04 20:25:59,209 [gitlabqm:issue] enrichment finished for https://gitlab.com/gitlab-org/gitlab-omnibus-builder
  2020-08-04 20:25:59,209 [gitlabqm:issue] enrichment starts for https://gitlab.com/gitlab-org/gitlab-pages
  2020-08-04 20:26:21,894 Error enriching raw from gitlabqm (https://gitlab.com/gitlab-org/gitlab-pages): 'search_fields'
Traceback (most recent call last):
  File "/home/p0tt3r/chaoss/sources/grimoirelab-elk/grimoire_elk/elk.py", line 530, in enrich_backend
    enrich_count = enrich_items(ocean_backend, enrich_backend)
  File "/home/p0tt3r/chaoss/sources/grimoirelab-elk/grimoire_elk/elk.py", line 318, in enrich_items
    total = enrich_backend.enrich_items(ocean_backend)
  File "/home/p0tt3r/chaoss/sources/grimoirelab-elk/grimoire_elk/enriched/qm/gitlabqm.py", line 302, in enrich_items
    self.extract_issue_metric(item)
  File "/home/p0tt3r/chaoss/sources/grimoirelab-elk/grimoire_elk/enriched/qm/gitlabqm.py", line 129, in extract_issue_metric
    project = self.extract_project(item)
  File "/home/p0tt3r/chaoss/sources/grimoirelab-elk/grimoire_elk/enriched/qm/gitlabqm.py", line 83, in extract_project
    return item['search_fields']['project']
KeyError: 'search_fields'
  2020-08-04 20:26:21,932 [gitlabqm] Done enrichment for https://gitlab.com/gitlab-org/gitlab-pages
  2020-08-04 20:26:21,933 [gitlabqm:issue] enrichment finished for https://gitlab.com/gitlab-org/gitlab-pages
  2020-08-04 20:26:21,933 [gitlabqm:issue] enrichment starts for https://gitlab.com/gitlab-org/gitlab-qa
  2020-08-04 20:28:37,923 1788 items inserted for GitLab QM
```

I'm investigating it and yet to find out the actual reason. I will update you on this.

EDIT: As I was creating this issue, I saw a few more similar errors for a set of projects. I'll be noting them here, might be useful later.

gitlabqm:issue
~~1. https://gitlab.com/gitlab-org/gitlab-pages~~
~~2. https://gitlab.com/gitlab-org/gitlab-runner~~
~~3. https://gitlab.com/gitlab-org/gitlab-services%2Fdesign.gitlab.com~~
~~4. https://gitlab.com/gitlab-org/gitlab-shell~~
~~5. https://gitlab.com/gitlab-org/gitlab-svgs~~
~~6. https://gitlab.com/gitlab-org/gitlab-triage~~
~~7. https://gitlab.com/gitlab-org/gitter%2Fwebapp~~

gitlabqm:merge
~~1. https://gitlab.com/gitlab-org/gitaly~~
~~2. https://gitlab.com/gitlab-org/gitlab-build-images~~
~~3. https://gitlab.com/gitlab-org/gitlab-runner~~
~~4. https://gitlab.com/gitlab-org/gitlab-shell~~
~~5. https://gitlab.com/gitlab-org/gitlab-svgs~~
~~6. https://gitlab.com/gitlab-org/gitlab-triage~~
~~7. https://gitlab.com/gitlab-org/gitlab-ui~~
~~8. https://gitlab.com/gitlab-org/gitlab-workhorse~~
~~9. https://gitlab.com/gitlab-org/gitlabktl~~
~~10. https://gitlab.com/gitlab-org/grafana-dashboards~~
~~11. https://gitlab.com/gitlab-org/omnibus-gitlab~~
~~12. https://gitlab.com/gitlab-org/security-products%2Fdast~~

meetup
~~1. GitLabANZ~~

EDIT 2: Fixed all the issues and got everything working correct.

**Comment by valeriocos** [comment]
Hi @vchrombie, the problem may be related to the fact that some raw items have been generated before https://github.com/chaoss/grimoirelab-perceval/commit/9b5a7accfd2824e2e0cc917ac8f968ba0c2db4f6, which introduced the attribute "search_fields".

We had a conversation time ago about using the attribute "origin" instead of "search_fields". If this is still not possible, a workaround is to modify the raw items to include the search_fields (it could be achieved with an update_by_query), wdyt?

**Comment by vchrombie** [comment]
> Hi @vchrombie, the problem may be related to the fact that some raw items have been generated before [chaoss/grimoirelab-perceval@9b5a7ac](https://github.com/chaoss/grimoirelab-perceval/commit/9b5a7accfd2824e2e0cc917ac8f968ba0c2db4f6), which introduced the attribute "search_fields".
> 
> We had a conversation time ago about using the attribute "origin" instead of "seharch_fields". If this is still not possible, a workaround is to modify the raw items to include the search_fields (it could be achieved with an update_by_query), wdyt?

Thanks for the reply @valeriocos. The workaround for using origin will work fine in this case. Let me check and get back to you.

EDIT: I have just finished the enrichment task and left out with only a few repositories (noted in my earlier reply). I will implement the workaround and try to sync everything. 

Completely off note, it almost took 4 and a half hours for enrichment. Wow, this is so enormous. :open_mouth:

**Comment by vchrombie** [comment]
pilot study :helicopter: on GitLab.org projects
data sources: gitlab, meetup

as the projects list is not similar, the study requires separate assessments for both the data sources. So, there will be two dashboards.

### gitlab data source dashboard

![Screenshot_20200805_180604](https://user-images.githubusercontent.com/25265451/89424884-ef960600-d755-11ea-86f3-eb058b909cfc.png)
![Screenshot_20200805_180617](https://user-images.githubusercontent.com/25265451/89425090-3126b100-d756-11ea-979a-5290accfda36.png)
![Screenshot_20200805_180653](https://user-images.githubusercontent.com/25265451/89425151-43a0ea80-d756-11ea-9f8b-608d5abd92cd.png)
![Screenshot_20200805_180703](https://user-images.githubusercontent.com/25265451/89425205-55828d80-d756-11ea-816d-c392beae2fb0.png)
![Screenshot_20200805_180711](https://user-images.githubusercontent.com/25265451/89425251-659a6d00-d756-11ea-9f33-56a1dd4f56bf.png)
![Screenshot_20200805_180724](https://user-images.githubusercontent.com/25265451/89425281-71862f00-d756-11ea-9e45-823389bf3fdd.png)
![Screenshot_20200805_180735](https://user-images.githubusercontent.com/25265451/89425330-7ea31e00-d756-11ea-8854-362ac183136b.png)

### meetup data source dashboard

![Screenshot_20200805_193613](https://user-images.githubusercontent.com/25265451/89425647-e22d4b80-d756-11ea-9931-e71ea3ad1767.png)
![Screenshot_20200805_193703](https://user-images.githubusercontent.com/25265451/89425735-fcffc000-d756-11ea-9c9b-75a6e6dc5182.png)
![Screenshot_20200805_193719](https://user-images.githubusercontent.com/25265451/89425797-0be67280-d757-11ea-8179-44b065587093.png)
![Screenshot_20200805_193730](https://user-images.githubusercontent.com/25265451/89425906-2a4c6e00-d757-11ea-8b03-5911a8120126.png)
![Screenshot_20200805_193821](https://user-images.githubusercontent.com/25265451/89425956-389a8a00-d757-11ea-855c-b6df27b270a8.png)
![Screenshot_20200805_193823](https://user-images.githubusercontent.com/25265451/89426006-4a7c2d00-d757-11ea-9d7e-55f20103c635.png)

**Comment by vchrombie** [comment]
QM Study for CHAOSS Community will be performed in two parts. As the metric working group repositories can't be compared with software projects, I have divided the list into two parts.

1. Software Project Study (grimoirelab projects, augur related, cregit and prospector) https://github.com/vchrombie/gsoc/issues/13#issuecomment-674579264
2. Metrics Working Groups Study (D&I, Risk, Common, Evolution, Value, and App Ecosystem WG) https://github.com/vchrombie/gsoc/issues/13#issuecomment-674579035

**Comment by vchrombie** [comment]
### QM Study for CHAOSS Community 

#### Metrics Working Groups Study

![Screenshot_20200817_005208](https://user-images.githubusercontent.com/25265451/90343145-7a66e280-e02b-11ea-8856-e692b2609dc0.png)
![Screenshot_20200817_005225](https://user-images.githubusercontent.com/25265451/90343146-7cc93c80-e02b-11ea-9691-58600d705d82.png)
![Screenshot_20200817_005420](https://user-images.githubusercontent.com/25265451/90343148-7dfa6980-e02b-11ea-9d4b-e347cf969875.png)
![Screenshot_20200817_005425](https://user-images.githubusercontent.com/25265451/90343151-7e930000-e02b-11ea-8c50-6fbdc667949a.png)

**Comment by vchrombie** [comment]
### QM Study for CHAOSS Community 

#### Software Projects Study

![Screenshot_20200817_012058](https://user-images.githubusercontent.com/25265451/90343171-9d919200-e02b-11ea-8a62-551cbff5f53c.png)
![Screenshot_20200817_012108](https://user-images.githubusercontent.com/25265451/90343175-9f5b5580-e02b-11ea-9353-639592c87e82.png)
![Screenshot_20200817_012116](https://user-images.githubusercontent.com/25265451/90343176-9ff3ec00-e02b-11ea-9a5c-f560f75f1acc.png)
![Screenshot_20200817_012122](https://user-images.githubusercontent.com/25265451/90343177-a1251900-e02b-11ea-9da0-9f1afc85d64c.png)
![Screenshot_20200817_012134](https://user-images.githubusercontent.com/25265451/90343178-a2564600-e02b-11ea-9b14-863b4afcb52c.png)
![Screenshot_20200817_012142](https://user-images.githubusercontent.com/25265451/90343179-a2eedc80-e02b-11ea-970d-995497144598.png)
![Screenshot_20200817_012146](https://user-images.githubusercontent.com/25265451/90343180-a4200980-e02b-11ea-8a9f-d55740a8cefa.png)

**Comment by vchrombie** [comment]
closing this issue as all the planned pilot studies have been completed
please feel free to open them if needed
