### ISSUE TITLE
 [tasks] periodo de codificación 3

### ISSUE THREAD

**Issue by vchrombie** [vchrombie/gsoc#17]
- [ ] Implement tests for the existing enrichers #15 

- [x] Update sirmordred repo with the configurations of the qm enrichers https://github.com/chaoss/grimoirelab-sirmordred/pull/486
- [x]  Add the qm results dashboard to sigils repository https://github.com/chaoss/grimoirelab-sigils/pull/470

- [x] case study with different organizations #13 
  - [x] gitlab.org - gitlabqm, meetupqm https://github.com/vchrombie/gsoc/issues/13#issuecomment-669236168
  - [x] chaoss githubqm, gitqm https://github.com/vchrombie/gsoc/issues/13#issuecomment-674578813

- [x] Implement githubqm enricher https://github.com/vchrombie/gsoc/issues/17#issuecomment-671612336

~~Implement slackqm enricher~~ (moved to wishlist)

- [x] Documentation for the project #20 

- [x] Work on tutorials, walk-through videos https://github.com/vchrombie/gsoc/issues/17#issuecomment-683490035

**Comment by vchrombie** [comment]
github:issue
![Screenshot_20200811_031737](https://user-images.githubusercontent.com/25265451/89835907-49963180-db83-11ea-8b35-901d5d3eada9.png)

github:pull
![Screenshot_20200811_031814](https://user-images.githubusercontent.com/25265451/89835914-4b5ff500-db83-11ea-99ba-cf06732f6210.png)

**Comment by valeriocos** [comment]
@vchrombie , can you update the description to include the upload of the qm dashboard to sigils?

Thanks

**Comment by vchrombie** [comment]
> @vchrombie , can you update the description to include the upload of the qm dashboard to sigils?

Sure @valeriocos.

**Comment by vchrombie** [comment]
### Work Video Demo

[![Work Demo](https://img.youtube.com/vi/RE9SRNY_a7g/0.jpg "Creating Quality models using GrimoireLab and CHAOSS metrics | GSoC 2020 | YouTube")](https://www.youtube.com/watch?v=RE9SRNY_a7g)
